<?php if ($this->u->days == 0): ?>
<div class="alert-message success">
	<p><?php echo sprintf($this->t->t('profile/birthdaytoday'), $this->u->username, $this->u->days) ?></p>
</div>
<?php elseif ($this->u->days < 7): ?>
<div class="alert-message">
	<p><?php echo sprintf($this->t->t($this->u->days == 1 ? 'profile/birthdaytomorrow' : 'profile/nextbirthday'), $this->u->username, $this->u->days) ?></p>
</div>
<?php endif; ?>

<div class="user-header" style="<?php echo $this->u->header ? 'background-image: url(' . $this->baseUrl() . $this->getConfig()->paths->headers . '/' . $this->u->uid . '.' . $this->u->header . ');' : '' ?>">
	<div class="media-grid avatar-profile">
		<a href="">
			<img src="<?php echo $this->baseUrl() . $this->getConfig()->paths->avatars . '/' . $this->u->uid . '.' . $this->u->avatar ?>" />
		</a>
	</div>
	<div class="header-username" style="<?php echo $this->u->namestyle ?>">
		<?php echo $this->u->username ?>
		<img rel="twipsy" data-placement="right" class="userstatus" src="<?php echo $this->baseUrl() . '/images/' . ($this->u->online == 1 ? 'online' : 'offline') . '.png' ?>" title="<?php echo $this->u->online == 1 ? sprintf($this->t->t('thread/online'), $this->u->username) : sprintf($this->t->t('thread/offline'), $this->u->username) ?>" />
	</div>
	<div class="header-lastactivity icon icon-time">
		<?php
		$time = round((time() - strtotime($this->u->last_activity)) / 60);
		
		if ($time <= 60) {
			$act = Users::printactivity($this->u->activity_text, $this->t);
			if ($act->link) {
				echo '<a href="' . $this->baseUrl() . $act->link . '" onclick="return loadpage(this)">' . $act->msg . '</a>';
			} else {
				echo $act->msg;
			}
			
			echo '<small>, ';
			echo $time == 0 || $time == 1 ? $this->t->t('useraction/timenow') : sprintf($this->t->t('useraction/time'), $time);
			echo '</small>';
		} else {
			echo '<small>' . $this->t->t('useraction/noaction') . '</small>';
		}
		?>
	</div>
</div>

<div class="user-infobars">
	<?php foreach ($this->activity as $i): ?>
		<div rel="twipsy" title="<?php echo sprintf($this->t->t('profile/points'), $i['points'], $i['total']) ?>" class="activitybar" style="height: <?php echo ceil($i['percent'] * 0.5) ?>px; margin-top: <?php echo floor(98 - ($i['percent'] * 0.5)) ?>px;">
			
		</div>
	<?php endforeach; ?>
</div>



<div class="row">
	<div class="span8 comments">
		<!-- guestbook -->
		<?php echo $this->render('user', 'form') ?>
	</div>
	<div class="span6">
		<div class="row userinfo">
			<div class="span3">
				<dl>
					<?php if ($this->u->birthday != '0000-00-00'): ?>
					<dt><?php echo $this->t->t('profile/birthday') ?></dt>
					<dd><?php echo floor((time() - strtotime($this->u->birthday)) / (3600 * 24 * 365)) ?></dd>
					<?php endif; ?>
					
					<dt><?php echo $this->t->t('profile/registered') ?></dt>
					<dd><?php echo Printdate::get(strtotime($this->u->regtime), $this->t) ?></dd>
					
					<dt><?php echo $this->t->t('profile/grade') ?></dt>
					<dd><?php echo $this->u->stylename ?></dd>
				</dl>
			</div>
			<div class="span3">
				<dl>
					<dt><?php echo $this->t->t('profile/threads') ?></dt>
					<dd><?php echo $this->cthreads ?></dd>
					
					<dt><?php echo $this->t->t('profile/comments') ?></dt>
					<dd><?php echo $this->ccomments ?></dd>
				</dl>
			</div>
		</div>
		
		<ul class="media-grid">
			<?php foreach ($this->threads as $t): ?>
				<li>
					<a href="<?php echo $this->baseUrl() ?>thread/<?php echo $t->ppid ? $t->ppid . '/?goto=' . $t->pid : $t->pid . '/' ?>" onclick="return loadpage(this)"><img src="<?php echo $this->baseUrl() . $t->thumbnail ?>" style="width: 122px; height: 91px" /></a>
				</li>
			<?php endforeach; ?>
		</ul>
	
		<div class="user-info">

			<div style="clear: both"></div>
			<div class="topvisits-box">
				<?php foreach ($this->threads as $t): ?><a href="<?php echo $this->baseUrl() ?>thread/<?php echo $t->ppid ? $t->ppid . '/?goto=' . $t->pid : $t->pid . '/' ?>" onclick="return loadpage(this)"><img src="<?php echo $this->baseUrl() . $t->thumbnail ?>" style="width: 122px; height: 91px" /></a><?php endforeach; ?>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$('*[rel=twipsy]').twipsy();
</script>