<!-- required scripts -->
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>javascripts/jquery/fileinput.js"></script>

<!-- required stylehsheets -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>styles/jquery/fileinput.css" />

<form class="avatarform" action="<?php echo $this->baseUrl() . 'settings/avatar' ?>" method="post" enctype="multipart/form-data">
	<fieldset>
		<div class="clearfix">
			<label for="username"><?php echo $this->t->t('settings/youravatar') ?></label>
			<div class="input">
				<img src="<?php echo $this->baseUrl() . $this->getConfig()->paths->avatars . '/' . $this->user['uid'] . '.' . $this->user['avatar'] ?>" style="width:90px;height:90px;padding:5px" /><img src="<?php echo $this->baseUrl() . $this->getConfig()->paths->avatars . '/' . $this->user['uid'] . '.' . $this->user['avatar'] ?>" style="width:50px;height:50px;padding:25px" /><img src="<?php echo $this->baseUrl() . $this->getConfig()->paths->avatars . '/' . $this->user['uid'] . '.' . $this->user['avatar'] ?>" style="width:30px;height:30px;padding:35px" />
			</div>
		</div>
		<div class="clearfix">
			<label for="username"><?php echo $this->t->t('settings/avatar') ?></label>
			<div class="input">
				<input type="file" name="avatar" id="file" />
				<script type="text/javascript">$('#file').customFileInput();</script>
			</div>
		</div>
		<div class="actions">
			<button name="save" class="btn primary" data-loading-text="<?php echo $this->t->t('settings/saving') ?>"><?php echo $this->t->t('settings/save') ?></button>
		</div>
	</fieldset>
</form>