<!-- required scripts -->
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>javascripts/jquery/fileinput.js"></script>

<!-- required stylehsheets -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>styles/jquery/fileinput.css" />

<?php if ($this->r->isPost() && !$this->error): ?>
<div class="alert-message block-message hide success" id="alert-message-settings">
	<a class="close" href="">&times;</a>
	<p><?php echo $this->t->t('settings/saved') ?></p>
</div>
<?php elseif ($this->error): ?>
<div class="alert-message block-message hide error" id="alert-message-settings">
	<a class="close" href="">&times;</a>
	<p><?php echo $this->t->t('settings/avatarerror') ?></p>
</div>
<?php endif; ?>

<script type="text/javascript">
	$('#alert-message-settings').fadeIn('fast');
	$(".alert-message").alert();
</script>

<form class="avatarform" action="<?php echo $this->baseUrl() . 'settings/avatar' ?>" method="post" enctype="multipart/form-data">
	<fieldset>
		<div class="clearfix">
			<label for="username"><?php echo $this->t->t('settings/youravatar') ?></label>
			<div class="input">
				<img src="<?php echo $this->baseUrl() . $this->getConfig()->paths->avatars . '/' . $this->user['uid'] . '.' . $this->user['avatar'] . '?' . time() ?>" style="width:90px;height:90px;padding:5px" /><img src="<?php echo $this->baseUrl() . $this->getConfig()->paths->avatars . '/' . $this->user['uid'] . '.' . $this->user['avatar'] . '?' . time() ?>" style="width:50px;height:50px;padding:25px" /><img src="<?php echo $this->baseUrl() . $this->getConfig()->paths->avatars . '/' . $this->user['uid'] . '.' . $this->user['avatar'] . '?' . time() ?>" style="width:30px;height:30px;padding:35px" />
			</div>
		</div>
		<div class="clearfix">
			<label for="file"><?php echo $this->t->t('settings/avatar') ?></label>
			<div class="input">
				<input type="file" name="avatar" id="file" />
				
				<script type="text/javascript">
				if (navigator.userAgent.search(/Firefox/) > -1) {
					$('#file').after('<button class="btn" data-loading-text="<?php echo $this->t->t('upload/uploading') ?>" id="filebutton" onclick="$(\'#file\').click(); return false;"><?php echo $this->t->t('upload/nofile') ?></button>');
					$('#file').hide();
				}
				</script>
			</div>
		</div>
		<div class="actions">
			<button name="save" class="btn primary" data-loading-text="<?php echo $this->t->t('settings/saving') ?>"><?php echo $this->t->t('settings/save') ?></button>
		</div>
	</fieldset>
</form>