<?php if ($this->r->isPost() && !$this->error): ?>
<div class="alert-message block-message hide success" id="alert-message-settings">
	<a class="close" href="">&times;</a>
	<p><?php echo $this->t->t('settings/saved') ?></p>
</div>
<?php elseif ($this->error): ?>
<div class="alert-message block-message hide error" id="alert-message-settings">
	<a class="close" href="">&times;</a>
	<p><?php echo $this->t->t('settings/passworderror') ?></p>
</div>
<?php endif; ?>

<script type="text/javascript">
	$('#alert-message-settings').fadeIn('fast');
	$(".alert-message").alert();
</script>

<form action="<?php echo $this->baseUrl() . 'settings/login/?ajax=1' ?>" method="post" onsubmit="return settingsform(this)">
	<fieldset>
		<div class="clearfix">
			<label for="username"><?php echo $this->t->t('settings/username') ?></label>
			<div class="input">
				<input disabled="disabled" type="text" name="username" value="<?php echo $this->login->username ?>" class="span6" />
			</div>
		</div>
		<div class="clearfix">
			<label for="email"><?php echo $this->t->t('settings/email') ?></label>
			<div class="input">
				<input id="email" type="text" name="email" value="<?php echo $this->login->email ?>" class="span6" />
			</div>
		</div>
		<div class="clearfix">
			<label for="password"><?php echo $this->t->t('settings/password') ?></label>
			<div class="input">
				<input id="password" type="password" name="password" value="" class="span6" />
			</div>
		</div>
		<div class="clearfix">
			<label for="passwordrepeat"><?php echo $this->t->t('settings/passwordrepeat') ?></label>
			<div class="input">
				<input id="passwordrepeat" type="password" name="passwordrepeat" value="" class="span6" />
			</div>
		</div>
		<div class="actions">
			<button name="save" class="btn primary" data-loading-text="<?php echo $this->t->t('settings/saving') ?>"><?php echo $this->t->t('settings/save') ?></button>
		</div>
	</fieldset>
</form>