<?php if ($this->r->isPost()): ?>
<div class="alert-message block-message hide success" id="alert-message-settings">
	<a class="close" href="">&times;</a>
	<p><?php echo $this->t->t('settings/saved') ?></p>
</div>
<?php endif; ?>

<script type="text/javascript">
	$('#alert-message-settings').fadeIn('fast');
	$(".alert-message").alert();
</script>

<form action="<?php echo $this->baseUrl() . 'settings/notifications/?ajax=1' ?>" method="post" onsubmit="return settingsform(this)">
	<fieldset>
		<div class="clearfix">
			<label><?php echo $this->t->t('settings/notis') ?></label>
			<div class="input">
				<ul class="inputs-list">
	                <li>
                  		<label>
                    		<input type="checkbox"<?php echo $this->notifications->notification_own == 1 ? ' checked="checked"' : '' ?> name="notification_own" value="1" />
                    		<span><?php echo $this->t->t('settings/threads') ?></span>
                  		</label>
	                </li>
	                <li>
                  		<label>
                    		<input type="checkbox"<?php echo $this->notifications->notification_other == 1 ? ' checked="checked"' : '' ?> name="notification_other" value="1" />
                    		<span><?php echo $this->t->t('settings/comments') ?></span>
                  		</label>
	                </li>
	                <li>
                  		<label>
                    		<input type="checkbox"<?php echo $this->notifications->notification_wall == 1 ? ' checked="checked"' : '' ?> name="notification_wall" value="1" />
                    		<span><?php echo $this->t->t('settings/wall') ?></span>
                  		</label>
	                </li>
	        	</ul>
			</div>
		</div>
		<div class="clearfix">
			<label><?php echo $this->t->t('settings/mailstitle') ?></label>
			<div class="input">
				<ul class="inputs-list">
	                <li>
                  		<label>
                    		<input type="checkbox"<?php echo $this->notifications->notification_own_mail == 1 ? ' checked="checked"' : '' ?> name="notification_own_mail" value="1" />
                    		<span><?php echo $this->t->t('settings/threads') ?></span>
                  		</label>
	                </li>
	                <li>
                  		<label>
                    		<input type="checkbox"<?php echo $this->notifications->notification_other_mail == 1 ? ' checked="checked"' : '' ?> name="notification_other_mail" value="1" />
                    		<span><?php echo $this->t->t('settings/comments') ?></span>
                  		</label>
	                </li>
	                <li>
                  		<label>
                    		<input type="checkbox"<?php echo $this->notifications->notification_wall_mail == 1 ? ' checked="checked"' : '' ?> name="notification_wall_mail" value="1" />
                    		<span><?php echo $this->t->t('settings/wall') ?></span>
                  		</label>
	                </li>
	        	</ul>
			</div>
		</div>
		
		<div class="alert-message block-message info">
			<p><?php echo sprintf($this->t->t('settings/emailhelp'), $this->baseUrl() . 'settings/login') ?></p>
		</div>
		<div class="actions">
			<button name="save" class="btn primary" data-loading-text="<?php echo $this->t->t('settings/saving') ?>"><?php echo $this->t->t('settings/save') ?></button>
		</div>
	</fieldset>
</form>

<!-- sometimes the button is disabled. ONLY in this form! I have no fuckin idea!! -->
<script type="text/javascript">
$('button[name=save]').removeAttr('disabled');
</script>