<?php if ($this->r->isPost()): ?>
<div class="alert-message block-message hide success" id="alert-message-settings">
	<a class="close" href="">&times;</a>
	<p><?php echo $this->t->t('settings/saved') ?></p>
</div>
<script type="text/javascript">
	$('#alert-message-settings').fadeIn('fast');
	$(".alert-message").alert();
</script>
<?php endif; ?>
<form action="<?php echo $this->baseUrl() . 'settings/profile/?ajax=1' ?>" method="post" onsubmit="return settingsform(this)">
	<fieldset>
		<div class="clearfix">
			<label for="homepage"><?php echo $this->t->t('settings/homepage') ?></label>
			<div class="input">
				<input id="homepage" type="text" name="homepage" value="<?php echo $this->profile->homepage ?>" class="span6" />
				<span class="help-block"><?php echo $this->t->t('settings/homepagehelp') ?></span>
			</div>
		</div>
		<div class="clearfix">
			<label for="hobbies"><?php echo $this->t->t('settings/hobbies') ?></label>
			<div class="input">
				<textarea id="hobbies" name="hobbies" class="span6"><?php echo $this->profile->hobbies ?></textarea>
			</div>
		</div>
		<div class="clearfix">
			<label for="birthday"><?php echo $this->t->t('settings/birthday') ?></label>
			<div class="input">
				<input id="birthday" type="text" name="birthday" value="<?php echo ($this->profile->birthday != '0000-00-00') ? date($this->t->t('main/date'), strtotime($this->profile->birthday)) : '' ?>" class="span3" />
				<span class="help-block"><?php echo $this->t->t('settings/birthdayhelp') ?></span>
			</div>
		</div>
		<div class="clearfix">
			<label><?php echo $this->t->t('settings/sex') ?></label>
			<div class="input">
				<ul class="inputs-list">
	                <li>
                  		<label>
                    		<input type="radio"<?php echo $this->profile->sex == 1 ? ' checked="checked"' : '' ?> name="sex" value="1" />
                    		<span><?php echo $this->t->t('settings/male') ?></span>
                  		</label>
	                </li>
	                <li>
                  		<label>
                    		<input type="radio"<?php echo $this->profile->sex == 2 ? ' checked="checked"' : '' ?> name="sex" value="2" />
                    		<span><?php echo $this->t->t('settings/female') ?></span>
                  		</label>
	                </li>
	                <li>
                  		<label>
                    		<input type="radio"<?php echo $this->profile->sex == 0 ? ' checked="checked"' : '' ?> name="sex" value="0" />
                    		<span><?php echo $this->t->t('settings/nosex') ?></span>
                  		</label>
	                </li>
	        	</ul>
			</div>
		</div>
		<div class="actions">
			<button name="save" class="btn primary" data-loading-text="<?php echo $this->t->t('settings/saving') ?>"><?php echo $this->t->t('settings/save') ?></button>
		</div>
	</fieldset>
</form>