<?php if(!$this->comment): ?>
<div class="page-header">
	<h2><?php echo $this->t->t('upload/disabledtitle') ?></h2>
</div>
<?php endif; ?>

<div class="alert-message block-message warning">
	<p><?php echo $this->t->t('upload/disabled') ?></p>
	<?php if ($this->getConfig()->upload->disabledmessage): ?>
	<p><?php echo $this->t->t($this->getConfig()->upload->disabledmessage) ?></p>
	<?php endif; ?>
</div>