<script type="text/javascript">
	function mediaclick() {
		$('#media .defaultmedia').removeClass('defaultmedia');
		$(this).addClass('defaultmedia');
	
		$.get(BASE_URL + 'upload/setdefault/' + $(this).find('img').data('media-id'));
	
		return false;
	}
	function deleteclick() {
		$(this).parent().parent().fadeOut('fast');

		$.get(BASE_URL + 'upload/delmedia/' + $(this).parent().find('img').data('media-id'));

		return false;
	};

	// does nothing yet, can check the uploadform before submitting 
	function upload(form) {
		return true;
	}

	function create(form) {
		var form = $(form);

		form.find('button[name=save]').button('loading');

		var warning = setTimeout(function() {
			$('#relax-message').fadeIn();
		}, 1000);
		
		$.post(form.attr('action'), form.serialize(), function(result) {
			clearTimeout(warning);
			
			var response = jQuery.parseJSON(result);

			if (response.error) {
				$('#modalerror .modal-body p').html(response.error);
				$('#modalerror').modal('show');

				$('#relax-message').hide();
				form.find('button[name=save]').button('reset');
			}

			if (response.forward) {
				loadlink(response.forward);
			}
		});

		// cancle regular form submit
		return false;
	}

	// callback for error while upload (shows a modal with errormsg)
	function adderror(msg) {
		$('#modalerror .modal-body p').html(msg);
		$('#modalerror').modal('show');

		// reset form
		$('#shareform')[0].reset();

		// reset localfile button
		$('#filebutton').button('reset');
	}

	// callback for iframe
	function addmedia(html) {
		var elem = $('<li style="display:none"></li>');
		var link = $('<a href="#" rel="twipsy" title="' + t.upload.makeprimary +'">' + html + '</a>');

		// add handlers
		link.click(mediaclick);
		link.find('.delete').click(deleteclick);
		
		elem.html(link);

		$('#mediacontainer').show();
		$('#media').append(elem);

		elem.fadeIn();

		// reset form
		$('#shareform')[0].reset();

		// reset localfile button
		$('#filebutton').button('reset');

		// add twipsy handler to new image
		$('*[rel=twipsy]').twipsy();
	}
</script>

<script type="text/javascript">
$(document).ready(function() {

	// if file changes, submit form instantly
	$('#file').change(function() {
		$('#filebutton').button('loading');
		$('#uploadform').submit();
	});

	// detect copy&paste
	$('#url').bind('paste', function() {
		var elem = $(this);
		setTimeout(function() {
			$('#shareform').submit();
		}, 100);
	});

	$('#media a').click(mediaclick);
	$('#media a .delete').click(deleteclick);
});
</script>

<div id="modalerror" class="modal hide fade">
	<div class="modal-header">
		<h3><?php echo $this->t->t('upload/errortitle') ?></h3>
	</div>
  	<div class="modal-body">
       	<p></p>
 	</div>
 	<div class="modal-footer">
		<a href="#" onclick="$(this).parent().parent().modal('hide'); $('input[name=username]').focus(); return false;" class="btn primary"><?php echo $this->t->t('login/closeerror') ?></a>
 	</div>
</div>

<div class="page-header">
	<h2><?php echo $this->t->t('upload/title') ?></h2>
</div>

<?php if(!$this->user): ?>
	<div class="alert-message block-message warning">
		<p><?php echo $this->t->t('upload/loggedout') ?></p>
	</div>
<?php endif; ?>

<!-- iframe used for upload -->
<iframe name="upload-iframe" class="upload-iframe"></iframe>

<?php echo $this->render('upload', 'uploadform') ?>

<form method="post" action="<?php echo $this->baseUrl() ?>upload/create" onsubmit="return create(this)">
	<fieldset>
		
		<legend><?php echo $this->t->t('upload/contenttitle') ?></legend>
		
		<div class="clearfix">
			<label for="comment"><?php echo $this->t->t('upload/writecomment') ?></label>
			<div class="input">
				<textarea id="comment" name="comment" rows="5" class="span6"></textarea>
			</div>
		</div>
		
		<div class="clearfix">
			<label><?php echo $this->t->t('upload/options') ?></label>
			<div class="input">
				<ul class="inputs-list">
	                <li>
                  		<label>
                    		<input type="checkbox" name="abothread" checked="checked" />
                    		<span data-placement="right" rel="twipsy" title="<?php echo $this->t->t('upload/abothreadhelp') ?>"><?php echo $this->t->t('upload/abothread') ?></span>
                  		</label>
	                </li>
	                <li>
                  		<label>
                    		<input type="checkbox" name="forwardthread" checked="checked" />
                    		<span><?php echo $this->t->t('upload/forwardthread') ?></span>
                  		</label>
	                </li>
	        	</ul>
			</div>
		</div>
		
		<div class="alert-message block-message warning hide" id="relax-message">
			<p><?php echo $this->t->t('upload/relax') ?></p>
		</div>

		<div class="actions">
			<button name="save" class="btn primary" data-loading-text="<?php echo $this->t->t('upload/saving') ?>"><?php echo $this->t->t('upload/publish') ?></button>
		</div>
		
	</fieldset>
</form>

<script type="text/javascript">	
	$('#comment').autoResize({
	    // On resize:
	    onResize : function() {
	        $(this).css({opacity:0.8});
	    },
	    // After resize:
	    animateCallback : function() {
	        $(this).css({opacity:1});
	    },
	    // Quite slow animation:
	    animateDuration : 300,
	    // More extra space:
	    extraSpace : 0,
	    limit : 400,
	});

	$('*[rel=twipsy]').twipsy();
</script>