<?php 

$formid = 'upload-form';
$buttondid = md5(microtime(true));

?>

<!-- required scripts -->
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>javascripts/jquery/fileinput.js"></script>

<!-- required stylehsheets -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>styles/jquery/fileinput.css" />

<script type="text/javascript">
	function submituploadform(form, target) {
		var form = $(form);
		form.find('.input-default').each(function() {
			$(this).val('');
		})

		return submitform(form, target);
	}
</script>

<h1 class="media-title">Upload</h1>
<iframe name="upload-iframe"></iframe> 
<!-- <p class="message">Bitte beachte die <a href="">Regeln</a> bevor du einen neuen Thread erstellst.</p> -->
	<div class="upload-media" id="upload-media">
		<ul class="media-navi">
			<li class="media-upload" id="media-upload"><a href="" class="icon icon-upload media-active">Hochladen</a></li>
			<li class="media-share" id="media-share"><a href="" class="icon icon-world">Remote</a></li>
		</ul>
		<div class="media-content media-upload-content">
			<form action="<?php echo $this->baseUrl() ?>upload/localfile" method="post" enctype="multipart/form-data" target="upload-iframe">
				<input type="file" name="file" id="file" />
			</form>
		</div>
		<div class="media-content media-share-content">
			<input type="text" name="url" class="share-url" id="share-url" class="input-default" value="http://www.youtube.com/watch?v=pWo5WqRVzdQ" /> <a href="" id="share-link" class="share-link">Share</a>
		</div>
	</div>
	<div class="media-shared" id="media-shared">
		
	</div>
<form class="upload <?php echo $formid ?>" method="post" action="<?php echo $this->baseUrl() ?>upload" onsubmit="return submituploadform(this, $('#layer-upload'))">
	<textarea name="comment" class="media-comment input-default">Einen Kommentar schreiben...</textarea>
	<input type="hidden" name="ppid" value="<?php echo $this->ppid ? $this->ppid : '' ?>" />
	<input type="hidden" name="replyto" value="<?php echo $this->replyto ? $this->replyto : '0' ?>" />
	<!-- <h2>Optionen</h2>
	<label><input type="checkbox" name="abothread" checked="checked" class="checkbox" />Thread abonnieren</label>
	<label><input type="checkbox" name="forwardthread" checked="checked" class="checkbox" />Thread nach dem Erstellen anzeigen</label> -->
	<div class="media-buttons">
		<!-- <div class="buttons-text">Vor dem posten bitte die Regeln lesen!</div> -->
		<input type="button" name="" value="Cancel" onclick="hideUpload()" class="button button-no" />
		<input type="submit" name="" value="<?php echo $this->comment ? $this->t->t('thread/publish') : $this->t->t('upload/publish') ?>" class="button button-yes" />
	</div>
</form>

<script type="text/javascript">
	var formid = '<?php echo $formid ?>';

	$('#file').customFileInput();

	$('.media-navi li a').click(function() {
		var elem1 = $('.media-navi li a.media-active');
		elem1.removeClass('media-active');
		$('.' + elem1.parent().attr('id') + '-content').hide();
	
		// Aktives element verstecken
		$('.' . cssClass + '-content').hide();
		
		$(this).addClass('media-active');
		$('.' + $(this).parent().attr('id') + '-content').show();
		return false;
	});
	
	$('#'+formid+' .share-link').click(function() {
		$('#'+formid+' .media-shared').hide();
		$('#'+formid+' .media-loading').show();
		
		var url = $('#'+formid+' .share-url');
		if (url.val()) {
			url.addClass('media-loading');
			$.get(baseUrl + 'upload/?share=1&' + url.serialize(), function(result) {
				$('#'+formid+' .upload-media').hide();
				$('#'+formid+' .media-shared').html(result);
				$('#'+formid+' .media-shared').fadeIn();
	
				$('#'+formid+' .media-loading').hide();
				$('#'+formid+' .media-shared').show();
				url.removeClass('media-loading');
				
			});
		} else {
			url.select();
		}
	
		// href abbrechen
		return false;
	});
	
	$('#'+formid+' .share-url').bind('paste', function() {
		var elem = $(this);
		setTimeout(function() {
			// click event auslösen wenn wir einen paste event bemerken
			$('#share-link').click();
		}, 100);
	});

	$('.media-comment').autoResize({
	    // On resize:
	    onResize : function() {
	        $(this).css({opacity:0.8});
	    },
	    // After resize:
	    animateCallback : function() {
	        $(this).css({opacity:1});
	    },
	    // Quite slow animation:
	    animateDuration : 300,
	    // More extra space:
	    extraSpace : 18,
	    limit : 400,
	});

	$('.input-default').mousedown(mouseevent);
	$('.input-default').focus(mouseevent);
</script>