<?php

if (!isset($_SESSION['media'])) {
	// create array if not exists
	$_SESSION['media'] = array();
}

if ($this->comment) {
	$publish = $this->t->t('upload/publishcomment');
} else {
	$publish = $this->t->t('upload/publish');
}

?>
<script type="text/javascript">
	function mediaclick() {
		$('#media .defaultmedia').removeClass('defaultmedia');
		$(this).addClass('defaultmedia');
	
		$.get(BASE_URL + 'upload/setdefault/' + $(this).find('img').data('media-id'));
	
		return false;
	}
	function deleteclick() {
		$(this).parent().fadeOut('fast');

		$.get(BASE_URL + 'upload/delmedia/' + $(this).parent().find('img').data('media-id'));

		return false;
	};

	// does nothing yet, can check the uploadform before submitting 
	function upload(form) {
		return true;
	}

	function create(form) {
		var form = $(form);

		form.find('button[name=save]').button('loading');
		form.find('button[name=cancel]').attr('disabled', 'disabled');

		var warning = setTimeout(function() {
			$('#relax-message').fadeIn();
		}, 1000);
		
		form.find('textarea.mention').mentionsInput('val', function(result) {
			$('textarea[name=content]').val(result);

			$.post(form.attr('action'), form.serialize(), function(result) {
				clearTimeout(warning);
				
				var response = jQuery.parseJSON(result);

				if (response.error) {
					$('#modalerror .modal-body p').html(response.error);
					$('#modalerror').modal('show');

					$('#relax-message').hide();
					form.find('button[name=save]').button('reset');
					form.find('button[name=cancel]').removeAttr('disabled');

					// if we have an error, reload captcha
					Recaptcha.reload();
				}

				if (response.forward) {
					loadlink(response.forward);
				}
			});
		});

		// cancle regular form submit
		return false;
	}

	// callback for error while upload (shows a modal with errormsg)
	function adderror(msg) {
		$('#modalerror .modal-body p').html(msg);
		$('#modalerror').modal('show');

		// reset form
		$('#shareform')[0].reset();

		// reset localfile button
		$('#filebutton').button('reset');
	}

	// callback for iframe
	function addmedia(html) {
		var elem = $('<li style="display:none"></li>');
		var link = $('<a href="#" rel="twipsy" title="' + t.upload.makeprimary +'">' + html + '</a>');

		// add handlers
		link.click(mediaclick);
		link.find('.delete').click(deleteclick);
		
		elem.html(link);

		$('#mediacontainer').show();
		$('#media').append(elem);

		elem.fadeIn();

		// reset form
		$('#shareform')[0].reset();

		// reset localfile button
		$('#filebutton').button('reset');

		// add twipsy handler to new image
		$('*[rel=twipsy]').twipsy();
	}
</script>
<script type="text/javascript">
function showRecaptcha(element) {
	Recaptcha.create("<?php echo $this->getConfig()->captcha->publickey ?>", element, {
		theme: "red",
		callback: Recaptcha.focus_response_field}
	);
}

$(document).ready(function() {

	// if file changes, submit form instantly
	$('#file').change(function() {
		$('#filebutton').button('loading');
		$('#uploadform').submit();
	});

	// detect copy&paste
	$('#url').bind('paste', function() {
		var elem = $(this);
		setTimeout(function() {
			$('#shareform').submit();
		}, 100);
	});

	$('#media a').click(mediaclick);
	$('#media a .delete').click(deleteclick);

	$('textarea.mention').mentionsInput({
	  onDataRequest:function (mode, query, callback) {
	    var data = [
	        <?php
	        $first = true;
	 		while(($user = $this->users->fetch_object()) != null) {
	 			echo (!$first ? ',' : '') . '{id:' . $user->uid . ', name:"' . $user->username . '", avatar:"' . $this->baseUrl() . $this->getConfig()->paths->avatars . '/' . $user->uid . '.' . $user->avatar . '"}';
	 			$first = false;
	 		}
	 		?>
	    ];
	
	    data = _.filter(data, function(item) { return item.name.toLowerCase().indexOf(query.toLowerCase()) > -1 });
	
	    callback.call(this, data);
	  }
	});
});
</script>

<div id="modalerror" class="modal hide fade">
	<div class="modal-header">
		<h3><?php echo $this->t->t('upload/errortitle') ?></h3>
	</div>
  	<div class="modal-body">
       	<p></p>
 	</div>
 	<div class="modal-footer">
		<a href="#" onclick="$(this).parent().parent().modal('hide'); $('input[name=username]').focus(); return false;" class="btn primary"><?php echo $this->t->t('login/closeerror') ?></a>
 	</div>
</div>


<?php if (!$this->comment): ?>
<div class="page-header">
	<h3><?php echo $this->t->t('upload/title') ?></h3>
</div>
<?php endif; ?>

<?php if(!$this->user): ?>
	<div class="alert-message block-message warning">
		<p><?php echo $this->t->t('upload/loggedout') ?></p>
	</div>
<?php endif; ?>

<!-- iframe used for upload -->
<iframe name="upload-iframe" class="upload-iframe"></iframe>

<?php echo $this->render('upload', 'uploadform') ?>

<form method="post" action="<?php echo $this->baseUrl() ?>upload/create" onsubmit="return create(this)">
	<fieldset>
		
		<legend><?php echo $this->t->t('upload/contenttitle') ?></legend>
		
		<div class="clearfix">
			<label for="comment"><?php echo $this->t->t('upload/writecomment') ?></label>
			<div class="input">
				<textarea name="comment" rows="5" class="span6 mention"></textarea>
				<textarea name="content" style="display:none"></textarea>
			</div>
		</div>
		
		<?php if (!$this->comment): ?>
		<div class="clearfix">
			<label for="categorie"><?php echo $this->t->t('upload/categorie') ?></label>
			<div class="input">
				<select name="categorie" id="categorie">
					<?php
						while (($tag = $this->tags->fetch_object()) != null) {
							echo '<option' . ($tag->default ? ' selected="selected"' : '') . ' value="' . 
									$tag->tid . '">' . $tag->value . '</option>';
						}
					?>
				</select>
			</div>
		</div>
		<?php endif; ?>
		
		<?php /* <div class="clearfix">
			<label><?php echo $this->t->t('upload/options') ?></label>
			<div class="input">
				<ul class="inputs-list">
	                <li>
                  		<label>
                    		<input type="checkbox" name="abothread" checked="checked" />
                    		<span data-placement="right" rel="twipsy" title="<?php echo $this->t->t('upload/abothreadhelp') ?>"><?php echo $this->t->t('upload/abothread') ?></span>
                  		</label>
	                </li>
	                <?php if (!$this->comment): ?>
	                <li>
                  		<label>
                    		<input type="checkbox" name="forwardthread" checked="checked" />
                    		<span><?php echo $this->t->t('upload/forwardthread') ?></span>
                  		</label>
	                </li>
	                <?php endif; ?>
	        	</ul>
			</div>
		</div> */ ?>
		
		<?php if ($this->getConfig()->upload->captcha && !isset($_SESSION['user']) && !isset($_SESSION['proved_as_a_human'])): ?>
		<div class="clearfix">
			<label><?php echo $this->t->t('register/captcha') ?></label>
			<div class="input" id="recaptcha">
				<?php //echo recaptcha_get_html($this->getConfig()->captcha->publickey) ?>
				<script type="text/javascript">	
				showRecaptcha('recaptcha');
				</script>
			</div>
		</div>
		<?php endif; ?>
		
		<div class="alert-message block-message warning hide" id="relax-message">
			<p><?php echo $this->t->t('upload/relax') ?></p>
		</div>
		
		<?php if ($this->comment): ?>
		<input type="hidden" name="ppid" value="<?php echo $this->ppid ?>" />
		<?php endif; ?>

		<div class="actions">
			<button name="save" class="btn primary" data-loading-text="<?php echo $this->t->t('upload/saving') ?>"><?php echo $this->t->t($publish) ?></button>
			<?php if ($this->comment): ?>
			<button name="cancel" class="btn" onclick="$('.commentbutton').fadeIn('fast'); $('.commentform').hide(); return false;"><?php echo $this->t->t('upload/cancel') ?></button>
			<?php endif; ?>
		</div>
		
	</fieldset>
</form>

<script type="text/javascript">	
$('*[rel=twipsy]').twipsy();
</script>