<?php

header("Content-Type: text/html; charset=UTF-8"); 
$size = getimagesize($this->media->image);
ob_start();

?>

<img src="<?php echo $this->baseUrl() . $this->media->thumbnail . '?' . time() ?>" data-media-id="<?php echo $this->key ?>" />
<span class="delete" rel="twipsy" data-placement="right" onmouseout="$(this).parent().twipsy('show')" onmouseover="$(this).parent().twipsy('hide')" title="<?php echo $this->t->t('upload/delmedia') ?>"></span>

<!-- <div id="content">
	<div class="share-thumb"><img src="<?php echo $this->baseUrl() . $this->media->thumbnail . '?' . time() ?>" /></div>
	<div class="share-data">
		<div class="share-name"><?php echo $this->media->getPlugin()->name() ?></div>
		<div class="share-source">
			<p><span class="thread-data"><?php echo $this->t->t('thread/size') ?></span><span class="thread-value"><?php echo $size[0] . 'x' . $size[1] ?></span></p>
			<p><span class="thread-data"><?php echo $this->t->t('thread/filename') ?></span><span class="thread-value"><?php echo htmlspecialchars(strip_tags(strlen($this->media->filename) > 15 ? substr($this->media->filename, 0, 12) . '...' . $this->media->image : $this->media->filename)) ?></span></p>
		</div>
		<br />
		<a href="" onclick="return cancel()" class="button button-icon icon icon-cancel"><span><?php echo $this->t->t('upload/cancel') ?></span></a>
	</div>
</div> -->

<?php

echo '<script type="text/javascript">parent.addmedia(\'' . str_replace(array("\t", "\r\n", "\r", "\n"), "", str_replace("'", "\\'", ob_get_clean())) . '\');</script>';

?>