<div class="upload-media" id="upload-media">
	<ul class="media-navi">
		<li class="media-upload" id="media-upload"><a href="" class="icon icon-upload media-active">Hochladen</a></li>
		<li class="media-share" id="media-share"><a href="" class="icon icon-world">Remote</a></li>
	</ul>
	<div class="media-content media-upload-content">
		<form action="<?php echo $this->baseUrl() ?>upload/localfile" method="post" enctype="multipart/form-data" target="upload-iframe">
			<input type="file" name="file" id="file" />
			<script type="text/javascript">$('#file').customFileInput();</script>
		</form>
	</div>
	<div class="media-content media-share-content">
		<input type="text" name="url" class="share-url" id="share-url" class="input-default" value="http://www.youtube.com/watch?v=pWo5WqRVzdQ" /> <a href="" id="share-link" class="share-link">Share</a>
	</div>
</div>
<script type="text/javascript">
$('.media-navi li a').click(medianaviclick = function() {
	var elem1 = $('.media-navi li a.media-active');
	elem1.removeClass('media-active');
	$('.' + elem1.parent().attr('id') + '-content').hide();

	// Aktives element verstecken
	$('.' . cssClass + '-content').hide();
	
	$(this).addClass('media-active');
	$('.' + $(this).parent().attr('id') + '-content').show();
	return false;
});

$('.share-link').click(function() {
	$('#'+formid+' .media-shared').hide();
	$('#'+formid+' .media-loading').show();
	
	var url = $('.share-url');
	if (url.val()) {
		url.addClass('media-loading');
		$.get(baseUrl + 'upload/?share=1&' + url.serialize(), function(result) {
			$('.upload-media').hide();
			$('.media-shared').html(result);
			$('.media-shared').fadeIn();

			$('.media-loading').hide();
			$('.media-shared').show();
			url.removeClass('media-loading');
			
		});
	} else {
		url.select();
	}

	// href abbrechen
	return false;
});
</script>