<div class="upload-media" id="upload-media">
	<ul class="media-navi">
		<li class="media-upload" id="media-upload"><a href="" class="icon icon-upload media-active">Hochladen</a></li>
		<li class="media-share" id="media-share"><a href="" class="icon icon-world">Remote</a></li>
	</ul>
	<div class="media-content media-upload-content">
		<form action="<?php echo $this->baseUrl() ?>upload/localfile" method="post" enctype="multipart/form-data" target="upload-iframe">
			<input type="file" name="file" id="file" />
			<script type="text/javascript">$('#file').customFileInput();</script>
		</form>
	</div>
	<div class="media-content media-share-content">
		<input type="text" name="url" class="share-url" id="share-url" class="input-default" value="http://www.youtube.com/watch?v=pWo5WqRVzdQ" /> <a href="" id="share-link" class="share-link">Share</a>
	</div>
</div>