<?php
foreach ($this->comments as $c):
	if (isset($c->media)) {
		$image = $this->getConfig()->paths->uploads  . '/' . 
			date('Ymd', strtotime($c->updatetime)) . '/' . 
			$c->mid . '.' . $c->image;
	
		$size = getimagesize($image);
	}
?>
<div class="row comment" id="post<?php echo $c->pid ?>">
	<div class="span3 commentinfo">
		<a href="<?php echo $this->baseUrl() ?>user/<?php echo $c->uid ?>/" class="username" style="<?php echo $c->namestyle ?>" onclick="return loadpage(this)"><?php echo $c->username ?></a>
		<img class="userstatus" src="<?php echo $this->baseUrl() . '/images/' . ($c->online == 1 ? 'online' : 'offline') . '.png' ?>" title="<?php echo $c->online == 1 ? sprintf($this->t->t('thread/online'), $c->username) : sprintf($this->t->t('thread/offline'), $c->username) ?>" data-placement="above" rel="twipsy" />
		<ul class="media-grid avatar">
			<li><a href="<?php echo $this->baseUrl() . 'user/' . $c->uid ?>/" onclick="return loadpage(this)">
				<img src="<?php echo $this->baseUrl() . $this->getConfig()->paths->avatars . '/' . $c->uid . '.' . $c->avatar ?>" />
			</a></li>
		</ul>
	</div>
	<div class="span11 commentcontent">
		<?php if (count($c->mediaset) > 0): ?>
		<ul class="media-grid">
			<?php foreach ($c->mediaset as $media): ?>
			<li><a href="<?php echo $this->baseUrl() . 'thread/' . $media->pid . '/' . (!$media->default ? $media->mid . '/' : '') ?>" onclick="return loadpage(this)"><img src="<?php echo $this->baseUrl() . $media->thumbnail ?>" width="90" height="90" /></a></li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>
		
		<p><?php echo $c->pid ?><?php echo ($c->pusername ? '<a href="#post' . $c->replyto . '">@' . $c->pusername . '</a> ' : '') . nl2br(htmlentities($c->content, ENT_QUOTES)) ?>
		<?php if($c->content) echo '<br />' ?><small><nobr><?php echo Printdate::get(strtotime($c->updatetime), $this->t) ?></nobr></small></p>
	</div>
</div>
<?php endforeach; ?>
<?php if ($this->active < $this->total): ?>
<div class="commentloader">
	<button class="btn" onclick="loadComments(); return false;" data-loading-text="<?php echo $this->t->t('thread/loadingcomments') ?>"><?php echo $this->t->t('thread/loadcomments') ?></button>
</div>
<?php endif; ?>

<script type="text/javascript">
$('.alert-message').alert();
$('*[rel=twipsy]').twipsy();
</script>