<?php

$size = getimagesize($this->media->image);
$user = $this->user;

?>
<div class="thread">
	<?php if($this->next): ?>
	<a id="next" href="<?php echo $this->baseUrl() . 'thread/' . $this->next ?>" onclick="return loadpage(this)">
		<?php echo $this->t->t('thread/next') ?>
	</a>
	<?php endif; ?>
	
	<?php if($this->prev): ?>
	<a id="prev" href="<?php echo $this->baseUrl() . 'thread/' . $this->prev ?>" onclick="return loadpage(this)">
		<?php echo $this->t->t('thread/prev') ?>
	</a>
	<?php endif; ?>

	<?php if (count($this->mediaset) > 1): ?>
	<ul class="media-grid" style="clear:both">
		<?php foreach ($this->mediaset as $media): ?>
		<li<?php echo $media->mid == $this->mid ? ' class="active"' : '' ?>>
			<a href="<?php echo $this->baseUrl() . 'thread/' . $this->pid . ($media->default == 1 ? '/' : '/' . $media->mid) ?>" onclick="return loadpage(this)">
				<span class="twipsy-arrow"></span>
				<img src="<?php echo $this->baseUrl() . $media->thumbnail ?>" />
			</a>
		</li>
		<?php endforeach; ?>
	</ul>
	<?php endif; ?>

	<div style="clear:both" class="image<?php echo $this->thread->astatus == 0 ? ' thread-image-deleted' : '' ?>">
		<?php if ($this->media->type == 4): ?>
			<iframe width="820" height="477" src="http://www.youtube.com/embed/<?php echo $this->media->extid ?>?rel=0" frameborder="0" allowfullscreen></iframe>
		<?php elseif ($this->media->type == 3): ?>
			<iframe src="http://player.vimeo.com/video/<?php echo $this->media->extid ?>?portrait=0&amp;color=1acfd9" width="820" height="615" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
		<?php else: ?>
			<a href="<?php echo $this->baseUrl() . $this->media->image ?>" title="<?php echo $this->t->t('thread/original') ?>" target="_blank">
				<img src="<?php echo $this->baseUrl() . $this->media->image ?>" <?php if ($size[0] > 820) { echo 'style="width: 820px"'; } ?> />
			</a>
		<?php endif; ?>
	</div>
	
	<?php if (isset($_SESSION['user'])): ?>
	<div class="info actions">
		<div class="rating">
			<button class="btn success<?php if ($this->rating && $this->rating->rating == 1) echo ' active'; ?>" rel="twipsy" data-placement="above" title="<?php echo $this->t->t('thread/like') ?>"><img src="<?php echo $this->baseUrl() ?>images/thumb_up.png" /><?php echo $this->t->t('thread/like') ?></button><button class="btn danger<?php if ($this->rating && $this->rating->rating == 0) echo ' active'; ?>" rel="twipsy" data-placement="above" title="<?php echo $this->t->t('thread/dislike') ?>"><img src="<?php echo $this->baseUrl() ?>images/thumb_down.png" /></button>
			
			<div class="bar">
				<div class="like" rel="twipsy" data-placement="below" title="<?php echo sprintf($this->t->t('thread/likes'), $this->ratingbar->likes) ?>" style="width: <?php echo round(148 * $this->ratingbar->like / 100) ?>px"></div>
				<div class="dislike" rel="twipsy" data-placement="below" title="<?php echo sprintf($this->t->t('thread/dislikes'), $this->ratingbar->dislikes) ?>" style="width: <?php echo round(148 * $this->ratingbar->dislike / 100) ?>px"></div>
			</div>
		</div>
		
		<div class="mediainfo">
			<!-- <button class="btn" rel="twipsy" title="<?php echo $this->t->t('thread/sharedescr') ?>"><?php echo $this->t->t('thread/share') ?></button> -->
			<?php if($user['uid'] == $this->thread->uid || $user['grade'] >= 8): ?>
				<?php if($user['grade'] >= 8 && $this->thread->astatus == 0): ?>
				<a href="" onclick="return postlink('<?php echo $this->baseUrl() ?>delete/', 'pid=<?php echo $this->thread->pid ?>&restore=1')" class="icon icon-restore"><?php echo $this->t->t('thread/restore') ?></a>
				<?php else: ?>
				<button onclick="$(this).twipsy('hide'); return loadlink('<?php echo $this->baseUrl() ?>delete/?pid=<?php echo $this->thread->pid ?>')" class="btn" rel="twipsy" title="<?php echo $this->t->t('thread/delete') ?>"><img src="<?php echo $this->baseUrl() ?>images/report.png" /></button>
				<?php endif; ?>
			<?php else: ?>
			<button onclick="$(this).twipsy('hide'); return loadlink('<?php echo $this->baseUrl() ?>report/?pid=<?php echo $this->thread->pid ?>')" class="btn" rel="twipsy" title="<?php echo $this->t->t('thread/report') ?>"><img src="<?php echo $this->baseUrl() ?>images/report.png" /></button>
			<?php endif; ?>
		</div>
		
		<p class="visits">
			<?php //echo $this->media->filename ? $this->media->filename . '  &bull; ' : '' ?>
			<?php echo sprintf($this->t->t($this->visits == 1 ? 'thread/visits' : 'thread/visitsplural'), $this->visits) ?>
		</p>
	
		<!-- <div class="buttons">
			<img src="<?php echo $this->baseUrl() ?>images/facebook.png" />
			<img src="<?php echo $this->baseUrl() ?>images/twitter.png" />
			<img src="<?php echo $this->baseUrl() ?>images/reddit.png" />
			<img src="<?php echo $this->baseUrl() ?>images/furl.png" />
			<img src="<?php echo $this->baseUrl() ?>images/delicious.png" />
		</div> -->
		
		<!-- :after { clear: both; } does not work for me -->
		<div style="clear:both"></div>
	</div>
	<?php endif; ?>
	
	<div class="row">
		
		<!-- comments -->
		<div class="span14 comments">
			<div class="row comment commentfirst">
				<div class="span3 commentinfo">
					<a href="<?php echo $this->baseUrl() . 'user/' . $this->thread->uid ?>/" onclick="return loadpage(this)" class="username" style="<?php echo $this->thread->namestyle ?>"><?php echo $this->thread->username ?></a>
					<img class="userstatus" src="<?php echo $this->baseUrl() . '/images/' . ($this->thread->online == 1 ? 'online' : 'offline') . '.png' ?>" data-placement="above" rel="twipsy" title="<?php echo $this->thread->online == 1 ? sprintf($this->t->t('thread/online'), $this->thread->username) : sprintf($this->t->t('thread/offline'), $this->thread->username) ?>" />
					<ul class="media-grid avatar">
						<li><a href="<?php echo $this->baseUrl() . 'user/' . $this->thread->uid ?>/" onclick="return loadpage(this)">
							<img src="<?php echo $this->baseUrl() . $this->getConfig()->paths->avatars . '/' . $this->thread->uid . '.' . $this->thread->avatar ?>" />
						</a></li>
					</ul>
				</div>
				<div class="span11 commentcontent">
					<p><?php echo nl2br(htmlentities($this->thread->content, ENT_QUOTES)) ?>
					<?php if($this->thread->content) echo '<br />' ?><small><nobr><?php echo Printdate::get(strtotime($this->thread->updatetime), $this->t) ?></nobr></small></p>
				</div>
			</div>
			
			<?php
			
			$this->comment = true;
			$this->ppid = $this->thread->pid;
			
			if ($this->getConfig()->upload->disabled) {
				echo '<div class="commentbutton">';
				echo $this->render('upload', 'error');
				echo '</div>';
			} elseif (!isset($_SESSION['user']) && !$this->getConfig()->upload->anonenabled) {
				echo '<div class="commentbutton">';
				echo $this->render('upload', 'anonerror');
				echo '</div>';
			} else {
				?>
				<div class="commentbutton">
					<button class="btn success" onclick="$('.commentform').fadeIn('fast'); $(this).parent().hide(); return false;"><?php echo $this->t->t('thread/writenew') ?></button>
				</div>
				
				<div class="commentform hide">
				<?php echo $this->render('upload', 'form'); ?>
				</div>
				<?php
			}
			
			?>
			
			<?php echo $this->render('thread', 'comments') ?>
		</div>
		
		<!-- thread info -->
		<!-- <div class="span4" >
			<h4><?php echo $this->t->t('thread/links') ?></h4>
			<?php if ($this->thread->astatus != 0): ?>
			<a href="" class="icon icon-favorite"><?php echo $this->t->t('thread/favorite') ?></a><br />
			<?php endif; ?>
			<?php if($user['uid'] == $this->thread->uid || $user['grade'] >= 8): ?>
				<?php if($user['grade'] >= 8 && $this->thread->astatus == 0): ?>
				<a href="<?php echo $this->baseUrl() ?>delete/?pid=<?php echo $this->thread->pid ?>&restore=1" onclick="return loadpage(this)" class="icon icon-restore"><?php echo $this->t->t('thread/restore') ?></a>
				<?php else: ?>
				<a href="<?php echo $this->baseUrl() ?>delete/?pid=<?php echo $this->thread->pid ?>" onclick="return loadpage(this)" class="icon icon-delete"><?php echo $this->t->t('thread/delete') ?></a>
				<?php endif; ?>
			<?php else: ?>
			<a href="" class="icon icon-report"><?php echo $this->t->t('thread/report') ?></a>
			<?php endif; ?>
			
			<h4><?php echo $this->t->t('thread/info') ?></h4>
			<ul>
				<li><?php echo $this->t->t('thread/visits') ?> <?php echo $this->visits ?></li>
				<li><?php echo $this->t->t('thread/size') ?> <?php echo $size[0] . 'x' . $size[1] ?></li>
				<li><?php echo $this->t->t('thread/filesize') ?> <?php echo Printsize::filesize($image) ?></li>
				<li><?php echo $this->t->t('thread/filename') ?> <?php echo htmlspecialchars(strip_tags(strlen($this->thread->filename) > 15 ? substr($this->thread->filename, 0, 12) . '...' . $this->thread->image : $this->thread->filename)) ?></li>
			</ul>
		</div>-->
	
	</div>
</div>
<script type="text/javascript">
$('.rating button').click(function() {
	$('.rating button').removeClass('active');

	if ($(this).hasClass('success')) {
		$.get(BASE_URL + 'rating/like/<?php echo $this->media->mid ?>/', rating);
	} else if ($(this).hasClass('danger')) {
		$.get(BASE_URL + 'rating/dislike/<?php echo $this->media->mid ?>/', rating);
	}
	
	$(this).addClass('active');
});

function rating(result) {
	var json = jQuery.parseJSON(result);

	if (json.like  || json.dislike) {
		$('.rating .bar').hide();

		//$('.rating .bar .like').twipsy({title:'new'});
		
		$('.rating .bar .like').attr('title', t.thread.likes.replace('%s', json.likes));
		$('.rating .bar .like').twipsy();

		$('.rating .bar .dislike').attr('title', t.thread.dislikes.replace('%s', json.dislikes));
		$('.rating .bar .dislike').twipsy();

		$('.rating .bar .like').css('width', Math.round(148 * json.like / 100));
		$('.rating .bar .dislike').css('width', Math.round(148 * json.dislike / 100));
		
		$('.rating .bar').fadeIn();

		$('.rating .bar .like, .rating .bar .dislike').twipsy();
	}
}

function loadCommentForm() {
	$.get('<?php echo $this->baseUrl() ?>upload/?form=1', function(html) {
		$('#comment-form').html(html);
	});
}

var page = 0;
function loadComments() {
	page = page + 1;

	$('.commentloader button').button('loading');
	
	$.get(BASE_URL + 'thread/<?php echo $this->thread->pid ?>/?load=' + page, function(result) {
		$('.commentloader').hide();

		var container = $('<div>' + result + '</div>');

		$('.comments').append(container);

		$('html, body').animate({
		    scrollTop: $(container.find('.comment').first()).offset().top  - 30
		}, 500);
	});
}

$('.alert-message').alert();
$('*[rel=twipsy]').twipsy();

$(document).unbind('keyup');
$(document).keyup(function(event) {
	if(!$('.commentform').is(':visible')) switch (event.which) {
		case 37: $('#next').click(); return false;
		case 39: $('#prev').click(); return false;
	}
});
</script>
<?php if (isset($_GET['goto'])): ?>
<script type="text/javascript">	
setTimeout(function() {
	$('html, body').animate({
	    scrollTop: $('#post<?php echo $_GET['goto'] ?>').offset().top
	}, 500);
}, 200);
</script>
<?php endif; ?>