<?php

$size = getimagesize($this->media->image);
$user = $this->user;

?>
<script type="text/javascript">
function loadCommentForm() {
	$.get('<?php echo $this->baseUrl() ?>upload/?form=1', function(html) {
		$('#comment-form').html(html);
	});
}

var page = 0;

function loadComments() {
	page = page + 1;
	
	$.get(BASE_URL + 'thread/<?php echo $this->thread->pid ?>/?load=' + page, function(result) {
		$('.comment-loader').hide();
		$('.thread-content').append(result);
	});
}

/*$(window).scroll(function(){
	if ($(window).scrollTop() == $(document).height() - $(window).height()){
		loadComments();
	}
});*/
</script>
<div class="thread">
	<?php if (count($this->mediaset) > 1): ?>
	<ul class="media-grid">
		<?php foreach ($this->mediaset as $media): ?>
		<li<?php echo $media->mid == $this->mid ? ' class="active"' : '' ?>>
			<a href="<?php echo $this->baseUrl() . 'thread/' . $this->pid . ($media->default == 1 ? '/' : '/' . $media->mid) ?>" onclick="return loadpage(this)">
				<span class="twipsy-arrow"></span>
				<img src="<?php echo $this->baseUrl() . $media->thumbnail ?>" />
			</a>
		</li>
		<?php endforeach; ?>
	</ul>
	<?php endif; ?>

	<div class="image<?php echo $this->thread->astatus == 0 ? ' thread-image-deleted' : '' ?>"><a href="<?php echo $this->baseUrl() . $image ?>" title="<?php echo $this->t->t('thread/original') ?>">
		<img src="<?php echo $this->baseUrl() . $this->media->image ?>" <?php if ($size[0] > 800) { echo 'style="width: 800px"'; } ?> />
	</a></div>
	
	<div class="row">
		
		<!-- comments -->
		<div class="span10">
			<div class="row comment commentfirst">
				<div class="span3 commentinfo">
					<a href="<?php echo $this->baseUrl() . 'user/' . $this->thread->uid ?>/" onclick="return loadpage(this)" class="username" style="<?php echo $this->thread->namestyle ?>"><?php echo $this->thread->username ?></a>
					<img class="userstatus" src="<?php echo $this->baseUrl() . '/images/' . ($this->thread->online == 1 ? 'online' : 'offline') . '.png' ?>" data-placement="above" rel="twipsy" title="<?php echo $this->thread->online == 1 ? sprintf($this->t->t('thread/online'), $this->thread->username) : sprintf($this->t->t('thread/offline'), $this->thread->username) ?>" />
					<ul class="media-grid avatar">
						<li><a href="<?php echo $this->baseUrl() . 'user/' . $this->thread->uid ?>/" onclick="return loadpage(this)">
							<img src="<?php echo $this->baseUrl() . $this->getConfig()->paths->avatars . '/' . $this->thread->uid . '.' . $this->thread->avatar ?>" />
						</a></li>
					</ul>
				</div>
				<div class="span7 commentcontent">
					<p><?php echo nl2br(htmlentities($this->thread->content, ENT_QUOTES)) ?>
					<br /><small><nobr><?php echo Printdate::get(strtotime($this->thread->updatetime), $this->t) ?></nobr></small></p>
				</div>
			</div>
			
			<div class="commentbutton">
			
				<button class="btn success" onclick="$('.commentform').fadeIn('fast'); $(this).parent().hide(); return false;"><?php echo $this->t->t('thread/writenew') ?></button>
			
			</div>
			
			<div class="commentform hide">
				<?php
				
				$this->comment = true;
				$this->ppid = $this->thread->pid;
				
				echo $this->render('upload', 'form');
				
				?>
			</div>
			
			<?php echo $this->render('thread', 'comments') ?>
		</div>
		
		<!-- thread info -->
		<!-- <div class="span4" >
			<h4><?php echo $this->t->t('thread/links') ?></h4>
			<?php if ($this->thread->astatus != 0): ?>
			<a href="" class="icon icon-favorite"><?php echo $this->t->t('thread/favorite') ?></a><br />
			<?php endif; ?>
			<?php if($user['uid'] == $this->thread->uid || $user['grade'] >= 8): ?>
				<?php if($user['grade'] >= 8 && $this->thread->astatus == 0): ?>
				<a href="<?php echo $this->baseUrl() ?>delete/?pid=<?php echo $this->thread->pid ?>&restore=1" onclick="return loadpage(this)" class="icon icon-restore"><?php echo $this->t->t('thread/restore') ?></a>
				<?php else: ?>
				<a href="<?php echo $this->baseUrl() ?>delete/?pid=<?php echo $this->thread->pid ?>" onclick="return loadpage(this)" class="icon icon-delete"><?php echo $this->t->t('thread/delete') ?></a>
				<?php endif; ?>
			<?php else: ?>
			<a href="" class="icon icon-report"><?php echo $this->t->t('thread/report') ?></a>
			<?php endif; ?>
			
			<h4><?php echo $this->t->t('thread/info') ?></h4>
			<ul>
				<li><?php echo $this->t->t('thread/visits') ?> <?php echo $this->visits ?></li>
				<li><?php echo $this->t->t('thread/size') ?> <?php echo $size[0] . 'x' . $size[1] ?></li>
				<li><?php echo $this->t->t('thread/filesize') ?> <?php echo Printsize::filesize($image) ?></li>
				<li><?php echo $this->t->t('thread/filename') ?> <?php echo htmlspecialchars(strip_tags(strlen($this->thread->filename) > 15 ? substr($this->thread->filename, 0, 12) . '...' . $this->thread->image : $this->thread->filename)) ?></li>
			</ul>
		</div>-->
	
	</div>
	
	<div class="thread-content">
		<div class="thread-info">
			<!-- <div class="thread-buttons">
				<div class="rate-up">
					<a href=""><?php echo $this->t->t('thread/rateup') ?></a>
				</div>
				<div class="rate-down">
					<a href=""></a>
				</div>
				<div style="clear: both"></div>
			</div> -->
			<?php if ($this->thread->astatus != 0): ?>
			<div class="thread-share">
				<img src="<?php echo $this->baseUrl() ?>images/facebook.png" />
				<img src="<?php echo $this->baseUrl() ?>images/twitter.png" />
				<img src="<?php echo $this->baseUrl() ?>images/reddit.png" />
				<img src="<?php echo $this->baseUrl() ?>images/furl.png" />
				<img src="<?php echo $this->baseUrl() ?>images/delicious.png" />
			</div>
			<?php endif; ?>
		</div>
		<?php if ($this->thread->astatus != 0): ?>
		<div class="comment">
			<div class="thread-user">
			</div>
			<div class="thread-text comment-form-disabled" id="comment-form">
				<?php
				
				$this->comment = true;
				$this->ppid = $this->thread->pid;
				
				//echo $this->render('upload', 'form');

				?>
			</div>
			<div style="clear: both"></div>
		</div>
		<?php endif; ?>
		
	</div>
</div>
<?php if (isset($_GET['goto'])): ?>
<script type="text/javascript">
$('html, body').animate({
    scrollTop: $('#post<?php echo $_GET['goto'] ?>').offset().top
}, 500);
</script>
<?php endif; ?>