<form action="<?php echo $this->baseUrl() . 'register' ?>" method="post" class="forgotpassword">
	<div class="page-header">
		<h2><?php echo $this->t->t('register/title') ?></h2>
	</div>
	
	<p><?php echo sprintf($this->t->t('register/help'), $this->getConfig()->contact->websitename) ?></p>
	
	<div class="alert-message block-message info">
		<p><?php echo $this->t->t('register/warning') ?></p>
	</div>
	
	<?php if (count($this->error) > 0): ?>
	<div id="alerterror" class="alert-message error">
		<a class="close" href="" onclick="$(this).parent().alert('close'); return false;">&times;</a>
		<p><?php echo $this->t->t('register/error') ?></p>
	</div>
	<?php endif; ?>
	
	<fieldset>
		<div class="clearfix<?php if (isset($this->error['username'])) echo ' error' ?>">
			<label for="registerusername"><?php echo $this->t->t('register/username') ?></label>
			<div class="input">
				<input type="text" id="registerusername" name="username" value="<?php echo $this->r->username ?>" class="span6" />
				
				<?php if (isset($this->error['username']) && $this->error['username'] !== true): ?>
				<span class="help-block"><?php echo $this->error['username'] ?></span>
				<?php endif; ?>
			</div>
		</div>
		<div class="clearfix<?php if (isset($this->error['email'])) echo ' error' ?>">
			<label for="register-email"><?php echo $this->t->t('register/email') ?></label>
			<div class="input">
				<input type="text" name="email" id="register-email" value="<?php echo $this->r->email ?>" class="span6" />
			</div>
		</div>
		<div class="clearfix<?php if (isset($this->error['password'])) echo ' error' ?>">
			<label for="register-password"><?php echo $this->t->t('register/password') ?></label>
			<div class="input">
				<input type="password" name="password" id="register-password" class="span6" />
			</div>
		</div>
		<div class="clearfix<?php if (isset($this->error['password'])) echo ' error' ?>">
			<label for="register-passwordrepeat"><?php echo $this->t->t('register/passwordrepeat') ?></label>
			<div class="input">
				<input type="password" name="passwordrepeat" id="register-passwordrepeat" class="span6" />
			</div>
		</div>
		<?php if ($this->getConfig()->register->captcha && !isset($_SESSION['proved_as_a_human'])): ?>
			<div class="clearfix<?php if (isset($this->error['captcha'])) echo ' error' ?>">
				<label><?php echo $this->t->t('register/captcha') ?></label>
				<div class="input">
					<?php echo recaptcha_get_html($this->getConfig()->captcha->publickey) ?>
				</div>
			</div>
		<?php endif; ?>
		<div class="actions">
			<button name="register" class="btn primary"><?php echo $this->t->t('register/button') ?></button>
		</div>
	</fieldset> 
</form>
<script type="text/javascript">
$('#registerusername').change(function() {
	$.get(BASE_URL + 'register/?checkusername=' + $('#registerusername').val(), function(result) {
		if (result == 1) {
			$('#registerusernamemsg').addClass('register-username-exists');
			$('#registerusernamemsg').removeClass('register-username-okay');
			$('#registerusernamemsg').html(t.register.exists);
		} else {
			$('#registerusernamemsg').addClass('register-username-okay');
			$('#registerusernamemsg').removeClass('register-username-exists');
			$('#registerusernamemsg').html(t.register.okay);
		}
	});
});
</script>