<!-- <div class="alert-message info">
	<p><?php echo sprintf($this->t->t('register/message'), $this->baseUrl() . 'register') ?></p>
</div> -->

<!--<div class="imageboard-filter">
	<div class="filter-selected"><?php echo $this->t->t('board/filter') ?> Hot Chicks</div>
	<ul class="filter-list filter-show">
		<?php foreach ($this->boards as $board): ?>
		<li class="filter-title"><?php echo $board->name ?></li>
			<?php foreach ($board->data as $board): ?>
				<li><a href=""><?php echo $board->name ?></a></li>
			<?php endforeach; ?>
		<?php endforeach; ?>
	</ul>
</div>-->
<div id="imageboard">
	<div class="pagination pagination-top">
		<?php echo $this->navigation->normaloutput() ?>
	</div>

	<?php echo $this->render('board', 'imageboard') ?>
	
	<div class="pagination pagination-bottom">
		<?php echo $this->navigation->normaloutput() ?>
	</div>
</div>
<script type="text/javascript">loadboard();</script>
<!-- gentime:<?php echo $this->time ?> -->