<div class="alert-message info">
	<p><button class="btn success" onclick="testBoard()">test</button><?php echo sprintf($this->t->t('register/message'), $this->baseUrl() . 'register') ?></p>
</div>

<div class="imageboard-navigation">
	<?php echo $this->navigation->normaloutput() ?>
</div>
<!--<div class="imageboard-filter">
	<div class="filter-selected"><?php echo $this->t->t('board/filter') ?> Hot Chicks</div>
	<ul class="filter-list filter-show">
		<?php foreach ($this->boards as $board): ?>
		<li class="filter-title"><?php echo $board->name ?></li>
			<?php foreach ($board->data as $board): ?>
				<li><a href=""><?php echo $board->name ?></a></li>
			<?php endforeach; ?>
		<?php endforeach; ?>
	</ul>
</div>-->
<div id="imageboard">
	<?php echo $this->render('board', 'imageboard') ?>
</div>
<div id="spacer"></div>
<div class="imageboard-navigation">
	<?php echo $this->navigation->normaloutput() ?>
</div>
<script type="text/javascript">loadboard();</script>
<!-- gentime:<?php echo $this->time ?> -->