<form action="<?php echo $this->baseUrl() . 'password' ?>" method="post" class="forgotpassword">
	<div class="page-header">
		<h2><?php echo $this->t->t('password/title') ?></h2>
	</div>
	<p><?php echo $this->t->t('password/help') ?></p>
	<fieldset>
		<div class="clearfix<?php echo $this->error ? ' error' : '' ?>">
			<label for="email"><?php echo $this->t->t('password/emailusername') ?></label>
			<div class="input">
				<input type="text" name="email" id="email" />
			</div>
		</div>
		<div class="actions">
			<input type="submit" class="btn primary" name="forgot" value="<?php echo $this->t->t('password/button') ?>" />
		</div>
	</fieldset> 
</form>