<form action="<?php echo $this->baseUrl() . 'password' ?>" method="post" class="forgotpassword">
	<div class="page-header">
		<h1><?php echo $this->t->t('password/title') ?></h1>
	</div>
	<p><?php echo $this->t->t('password/help') ?></p>
	<fieldset>
		<label for="email"><?php echo $this->t->t('password/emailusername') ?></label>
		<div class="input">
			<input type="text" name="email" id="email" />
		</div>
		<div class="actions">
			<input type="submit" class="btn primary" name="forgot" value="<?php echo $this->t->t('password/button') ?>" />
		</div>
	</fieldset> 
</form>