<?php

/**
 * Das hier ist das Haupttemplate, dieses wird aufgerufen wenn der Benutzer
 * die Seite direkt aufruft. Bei einem Aufruf via Ajax wird dieses Template
 * nicht aufgerufen, nur der Teil für "column-board-content".
 * 
 * Hier werden Javascripts und CSS-Definitionen geladen die allgemein Gültigkeit
 * haben. Spezifische Scripts sollten direkt in den Templates der Module
 * eingefügt werden.
 * 
 * @author benn0r <benjamin@benn0r.ch>
 * @since 10122011
 * @version 10122011
 */

?>
<!DOCTYPE html>
<html>
<head>
	<title><?php echo time() ?></title>
	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<script type="text/javascript">
	<?php
		// print all translations for javascript
		// json_encode from php does not work in internet explorer? (tested in ie9)
		$o = 'var t = {';
		foreach ($this->t->getContents() as $key => $arr) {
			$o .= '"' . $key . '":{';
			foreach ($arr as $key => $txt) {
				$o .= '"' . $key . '":"' . str_replace('\\', '\\\\', $txt) . '",';
			}
			$o = substr($o, 0, -1) . '},';
		}
		
		echo substr($o, 0, -1) . '};';
	?>
	</script>
	
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>lib/bootstrap/bootstrap.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>styles/default/main.css" />
	
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>javascripts/jquery.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>javascripts/jquery.autoresize.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>javascripts/imageboard.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>javascripts/jquery/davis.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>javascripts/jquery/inlog.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>lib/bootstrap/buttons.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>lib/bootstrap/modal.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>lib/bootstrap/twipsy.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>lib/bootstrap/popover.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>lib/bootstrap/alert.js"></script>
	
	<link rel="icon" href="<?php echo $this->baseUrl() ?>images/favicon.ico" type="image/x-icon" />

	<script type="text/javascript">

		var BASE_URL = '<?php echo $this->baseUrl() ?>';
		var NTIME = '<?php echo time() - 10 ?>';
		var TIME = '<?php echo time() ?>';

		/*if(document.location.href.replace('#!', '') != document.location.href) {
			redirect = document.location.href.substring(
					document.location.href.search('#!') + 2,
					document.location.href.length
			);
			document.location.href = BASE_URL + redirect;
		}

		if (typeof history.pushState != 'undefined') {
			window.onpopstate = function(e) {
				if (location.href.replace.('#!').search('#') <= 0) {
					var link = document.location.href.replace(BASE_URL, '');
					loadlink(BASE_URL + link);
				}
			};
		} else {
			var lastlink = null;
			
			function observeLink() {
				if (lastlink != null) {
					if(document.location.href.replace('#!', '') != document.location.href) {
						redirect = document.location.href.substring(
								document.location.href.search('#!') + 2,
								document.location.href.length
						);
					} else {
						redirect = document.location.href.replace(BASE_URL, '');
					}
					
					if (redirect != lastlink) {
						loadLink(redirect, false);
					}
				}
				setTimeout('observeLink()', 300);
			}
			observeLink();
		}*/

		var activetime = NTIME;
		var notificationsTimer = setInterval(notifications = function notifications() {
			$.getJSON(BASE_URL + 'notifications/?time=' + activetime, function(data) {

				if (data.users.length == 0) {
					$('.mainpage-users-container').hide();
				} else {
					$('.mainpage-users-container').show();
					$('.mainpage-users').html('');
					
					for (var i = 0; i < data.users.length; i++) {
						var u = data.users[i];
						
						$('.mainpage-users').append('<a onclick="return loadpage(this)" title="' + u.username + '" href="' + BASE_URL + 'user/' + u.uid + '/"><img src="' + u.avatar + '"</a>');
					}
				}

				for (var i = 0; i < data.news.length; i++) {
					var n = data.news[i];

					var elem = $('<li><h5>' + n.inserttime + '</h5>' + n.text + '</li>');
					elem.hide();
					$('.mainpage-news').prepend(elem);
					elem.fadeIn('slow');
				}

				activetime = data.next;
			});
		}, 10000);

		// update notifications
		//notifications();

		function loadpage(link) {
			var elem = $(link);

			return loadlink(elem.attr('href'));
		}
		function loadlink(uri) {
			$('.loading').fadeIn('fast');
			var link = uri.replace(BASE_URL, '');

			lastlink = link;

			if (typeof history.pushState != 'undefined') {
				history.pushState({foo: 'bar'}, uri, uri);
			} else {
				document.location.href = '#!' + link;
			}

			if (uri.indexOf('?') > 0) {
				uri = uri + '&ajax=1';
			} else {
				uri = uri + '/?ajax=1';
			}

			$.get(uri, function(result) {
				$('.content .container').html(result);
				$('.loading').hide();
			});

			<?php if (!$this->user): ?>
			// update login-forward
			$('#login-forward').val(document.location.href);
			<?php endif; ?>

			return false;
		}
		function submitform(form, target) {
			var form = $(form);

			if (form.attr('method') == 'post') {
				$.post(form.attr('action'), form.serialize(), function(result) {
					target.html(result);
				});
			}

			// onsubmit cancel
			return false;
		}
		function submitlogin(form) {
			var form = $(form);

			if (form.find('input[value=]').size() > 0) {
				form.find('input[value=]').first().select();
				return false;
			}

			form.find('button').button('loading');
			form.find('.alert-message').remove();

			$.post(BASE_URL + 'login', $(form).serialize(), function(result) {
				if (result == 0) {
					$('#modal-loginerror').modal('show');

					// clear loginform
					form.find('input').val('');

					// reset submit button state
					form.find('button').button('reset');
				} else {
					// login successful
					document.location = document.location;
				}
			});
			return false;
		}

		var timeout = null;
		function timer(img) {
			if (timeout) {
				clearTimeout(timeout);
			}
			timeout = setTimeout(function() {
				if ($(img).find('.image-small').width() < $(img).find('.image-large').width()) {
										
					//$(img).find('.image-large').animate({width: 142, height: 206}, 500);
					
					$(img).addClass('active');
					
					$(img).css('margin-left', '-' + ((154 - $(img).find('.image-small').width()) / 2) + 'px');
					$(img).css('margin-top', '-' + ((218 - $(img).find('.image-small').height()) / 2) + 'px');
	
					$(img).mouseleave(function() {
						$(img).removeClass('active');
	
						$(img).css('margin-left', '2px');
						$(img).css('margin-top', '2px');
					});
				} else {
					$(img).addClass('activelarge');

					$(img).mouseleave(function() {
						$(img).removeClass('activelarge');
					});
				}
			}, 300);
		}
		function stoptimer(img) {
			clearTimeout(timeout);
		}
		function board() {
			if(document.getElementById('imageboard')) {
				var board = new Imageboard('imageboard', 'spacer');
				var rightheight = null;

				board.bufferright = 0;
				board.dispatchAfterImage = function(image, startcoord, endcoord) {
				}
				board.isImageValid = function(image) {
					if(parseInt(image.id) == image.id) {
						return true;
					}
					return false;
				}
				board.dispatchAfterImages = function() {
					document.getElementById(this.spacerid).style.height = this.rheight + this.unit;
				}
				resize = function() {
					board.resize();
				}
				resize();
				
				document.getElementById('imageboard').style.visibility = '';
				window.onresize = resize;
			}
		}
	</script>
	
	<script type="text/javascript">
	var baseUrl = '<?php echo $this->baseUrl() ?>';
	
	function scrollbar(element) {
		element.jScrollPane();
	}

	var mouseevent = function() {
		$(this).removeClass('input-default');
		$(this).val('');

		$(this).unbind('mousedown');
		$(this).unbind('focus');

		var e = $(this);

		if ($(this).hasClass('input-default-password')) {
			
			var n = $('<input type="password" name="'+e.attr('name')+'" class="'+e.attr('class')+'" />');
			
			e.after(n);
			e.remove();

			setTimeout(function () {
				n.focus();
			}, 10);
		}

		setTimeout(function () {
			e.focus();
		}, 10);
	};

	function search() {
		$.get(BASE_URL + 'search/' + $('.search input[type=text]').val(), function(result) {
			var results = jQuery.parseJSON(result);
			var container = $('.searchresults');
			
			for (var i = 0; i < results.length; i++) {
				container.append('<div class="searchresult"><h4>' + results[i].content + '</h4><p>' + results[i].content + '</p></div>');
			}
		});
	}

	$(document).ready(function() {
		<?php if (!$this->user): ?>
		// update login-forward
		$('#login-forward').val(document.location.href);
		<?php endif; ?>

		$('.search-input').bind('paste', function() {
			var elem = $(this);
			setTimeout(function() {
				var regexp = /^(([\w]+:)?\/\/)?(([\d\w]|%[a-fA-f\d]{2,2})+(:([\d\w]|%[a-fA-f\d]{2,2})+)?@)?([\d\w][-\d\w]{0,253}[\d\w]\.)+[\w]{2,4}(:[\d]+)?(\/([-+_~.\d\w]|%[a-fA-f\d]{2,2})*)*(\?(&?([-+_~.\d\w]|%[a-fA-f\d]{2,2})=?)*)?(#([-+_~.\d\w]|%[a-fA-f\d]{2,2})*)?$/;
				if (regexp.test(elem.val())) {
					$('#quickresult-share').fadeIn();
				} else {
					$('#quickresult-share').hide();
				}
			}, 100);
		});
		$('.search-input').keydown(function() {
			$('.search-quickresult').show();
		});

		$('.modal').modal({'backdrop':'static'});

		//$('#modal-upload').modal({'backdrop':'static'});
		//$('#modal-upload').modal('show');

		$('.alert-message').alert();
		$('*[rel=twipsy]').twipsy();

		search();
	});
	</script>
</head>
<body>
	<div class="header">
		<h5 class="logo"></h5>
				
		<!-- <ul class="nav">
			<li><a href=""><?php echo $this->t->t('navi/upload') ?></a></li>
			<li><a href=""><?php echo $this->t->t('navi/profile') ?></a></li>
			<li><a href=""><?php echo $this->t->t('navi/settings') ?></a></li>
			<?php if (!$this->user): ?>
			<li><a href="<?php echo $this->baseUrl() ?>register" class="btn large"><?php echo $this->t->t('register/link') ?></a></li>
			<?php endif; ?>
		</ul> -->
		
		<form class="pull-left search" method="post">
			<input type="text" autocomplete="off" onclick="$(this).select()" name="search" value="benn0r" />
			<div class="searchresults">
				
			</div>
		</form>
	</div>
	
	<div class="loading hide">
		<p><span></span><?php echo $this->t->t('header/loading') ?></p>
	</div>
	
	<div id="modal-upload" class="modal hide fade">
    	<div class="modal-header">
        	<h3><?php echo $this->t->t('login/errortitle') ?></h3>
        </div>
   		<div class="modal-body">
        	<p><?php echo sprintf($this->t->t('login/errortext'), $this->baseUrl() . 'password') ?></p>
  		</div>
   		<div class="modal-footer">
			<a href="#" onclick="$(this).parent().parent().modal('hide'); $('input[name=username]').focus(); return false;" class="btn primary"><?php echo $this->t->t('login/closeerror') ?></a>
    	</div>
	</div>
	
	<div class="container-fluid">
		<div class="sidebar">
			<?php if (!$this->user): ?>
			<!-- <h5><?php echo $this->t->t('login/title') ?></h5> -->
			<form method="post" class="login" action="<?php echo $this->baseUrl() ?>login" onsubmit="return submitlogin(this)">
				<input type="text" class="span3" name="username" placeholder="<?php echo $this->t->t('login/username') ?>" />
				<input type="password" class="span3" name="password" placeholder="<?php echo $this->t->t('login/password') ?>" />
				<button class="btn primary" data-loading-text="Loading..." name="login"><?php echo $this->t->t('login/send') ?></button>
			</form>
			
			
			<div id="modal-loginerror" class="modal hide fade">
            	<div class="modal-header">
              		<h3><?php echo $this->t->t('login/errortitle') ?></h3>
            	</div>
            	<div class="modal-body">
              		<p><?php echo sprintf($this->t->t('login/errortext'), $this->baseUrl() . 'password') ?></p>
            	</div>
            	<div class="modal-footer">
              		<a href="#" onclick="$(this).parent().parent().modal('hide'); $('input[name=username]').focus(); return false;" class="btn primary"><?php echo $this->t->t('login/closeerror') ?></a>
            	</div>
			</div>
				
			
			<h5><?php echo $this->t->t('navi/title') ?></h5>
			<ul class="mainpage-links">
				<li><a href="<?php echo $this->baseUrl() ?>register" class="icon-register"><?php echo $this->t->t('register/link') ?></a></li>
				<li><a href="<?php echo $this->baseUrl() ?>password" class="icon-register"><?php echo $this->t->t('login/passwordforgot') ?></a></li>
			</ul>
			<?php else: ?>
			<div class="userbox">
				<div class="media-grid">
				<a href="<?php echo $this->baseUrl() . 'user/' . $this->user['uid'] ?>" onclick="return loadpage(this)">
					<img class="avatar-small" src="<?php echo $this->baseUrl() . $this->getConfig()->paths->avatars ?>/<?php echo $this->user['uid'] . '.' . $this->user['avatar'] ?>" />
				</a>
				</div>
				<div class="username">
					<a href="<?php echo $this->baseUrl() . 'user/' . $this->user['uid'] ?>" onclick="return loadpage(this)"><?php echo $this->user['username'] ?></a>
				</div>
				
				<div style="clear: both"></div>
			</div>
			<h5><?php echo $this->t->t('navi/title') ?></h5>
			<ul class="mainpage-links">
				<li><a href="" onclick="return showUpload()" class="icon-upload"><?php echo $this->t->t('navi/upload') ?></a></li>
				<li><a onclick="return loadpage(this)" href="<?php echo $this->baseUrl() . 'user/' . $this->user['uid'] ?>" class="icon-profile"><?php echo $this->t->t('navi/profile') ?></a></li>
				<li><a href="<?php echo $this->baseUrl() . 'notifications' ?>" class="icon-notifications"><?php echo $this->t->t('navi/notifications') ?></a></li>
				<li><a href="<?php echo $this->baseUrl() . 'settings' ?>" class="icon-settings"><?php echo $this->t->t('navi/settings') ?></a></li>
				<li><a href="<?php echo $this->baseUrl() . 'logout' ?>" class="icon-logout"><?php echo $this->t->t('navi/logout') ?></a></li>
			</ul>
			<div class="mainpage-users-container">
				<h5><?php echo $this->t->t('user/active') ?></h5>
				<div class="mainpage-users">
					
				</div>
			</div>
			
			<?php endif; ?>
			<h5><?php echo $this->t->t('news/title') ?></h5>
			<ul class="mainpage-news">
				<?php 
				$news = new News();
				
				$news = $news->fetch();
				while (($n = $news->fetch_object()) != null):
				?>
				<li><h5><?php echo Printdate::get(strtotime($n->inserttime), $this->t) ?></h5><?php echo $n->text ?></li>
				<?php endwhile; ?>
			</ul>
		</div>
		
		<div class="content">
			<div class="container">
				<?php $this->render($this->module, $this->action) ?>
			</div>
		</div>
	</div>

</body>
</html>