<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title></title>
	
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>styles/jscrollpane.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>styles/shoutbox.css" />
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>javascripts/jquery.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>javascripts/jquery.mousewheel.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>javascripts/tinyscrollbar.js"></script>
	<script type="text/javascript">
	
		$(document).ready(function() {
			scrollbar($('.shoutbox-content'));
		});
		
		function scrollbar(element) {
			element.jScrollPane();
		}
		
	</script>
	
</head>
<body>
	
	<div class="shoutbox-content">
		<div class="content-inline">
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
			adsf<br />
		</div>
	</div>
	<div class="shoutbox-list">
	</div>
	<div class="shoutbox-form">
		<form action="" method="post">
			<input type="text" name="text" class="form-text" /><a href="" class="form-send">Send</a>
		</form>
	</div>

</body>
</html>